### ISSUE TITLE
Implementation of UMBRELLA concepts

### ISSUE THREAD

**Issue by mcanini** [h2020-endeavour/endeavour#8]

**Comment by mcanini** [comment]
We will start from the public repo of Umbrella: https://github.com/umbrella-fabric/TouSIX-Manager

**Comment by mcanini** [comment]
@ederlf I have the following error running this.

`root@endeavour:~/endeavour# ryu-manager umbrella/umbrella.py --config-file umbrella/fabric.cfg
loading app umbrella/umbrella.py
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 9, in <module>
    load_entry_point('ryu==3.30', 'console_scripts', 'ryu-manager')()
  File "/usr/local/lib/python2.7/dist-packages/ryu/cmd/manager.py", line 88, in main
    app_mgr.load_apps(app_lists)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 401, in load_apps
    cls = self.load_app(app_cls_name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/base/app_manager.py", line 378, in load_app
    mod = utils.import_module(name)
  File "/usr/local/lib/python2.7/dist-packages/ryu/utils.py", line 91, in import_module
    __import__(name)
  File "/home/vagrant/endeavour/umbrella/umbrella.py", line 1, in <module>
    from oslo.config import cfg
ImportError: No module named oslo.config`

We need to install oslo automatically during provisioning.

**Comment by ederlf** [comment]
For a quick fix

```
$sudo apt-get install python-oslo.config
```

I will add it to the vagrant  provisioning today.
